### ISSUE TITLE
No such column pKa_relu in input file

### ISSUE THREAD

**Issue by zengjianyou** [zhenglz/onionnet#9]
I successfully extracted your features, but an error occurred during my training,
errors:
No such column pKa_relu in input file
![image](https://user-images.githubusercontent.com/34835647/105141662-71c38c80-5b34-11eb-92e9-9855ed34b416.png)

**Comment by zhenglz** [comment]
please show me the header of the feature file, I mean the first line of the
file, The col contains the real label (experimental pKx) should be named as
"pKa_true".

**Comment by zengjianyou** [comment]
There are still problems in extracting the data features of individual training sets，
error：

Traceback (most recent call last):
  File "generate_features.py", line 307, in <module>
    r, ele_pairs = generate_features(fn, lig_code, n_cutoffs)
  File "generate_features.py", line 205, in generate_features
    cplx.distance_pairs()
  File "generate_features.py", line 121, in distance_pairs
    self.distance_matrix_ = mt.compute_distances(self.pdb, atom_pairs=all_pairs)[0]
  File "/home/zjy/miniconda3/envs/drug_drug/lib/python3.6/site-packages/mdtraj/geometry/distance.py", line 62, in compute_distances
    pairs = ensure_type(atom_pairs, dtype=np.int32, ndim=2, name='atom_pairs', shape=(None, 2), warn_on_cast=False)
  File "/envs/drug_drug/lib/python3.6/site-packages/mdtraj/utils/validation.py", line 123, in ensure_type
    "You supplied %s" % (name, ndim, val.ndim)))
ValueError: atom_pairs must be ndim 2. You supplied 1

ValueError: atom_pairs must be ndim 2. You supplied 1

**Comment by zengjianyou** [comment]
@zhenglz  
There are still problems in extracting the data features of individual training sets，
error：

Traceback (most recent call last):
File "generate_features.py", line 307, in
r, ele_pairs = generate_features(fn, lig_code, n_cutoffs)
File "generate_features.py", line 205, in generate_features
cplx.distance_pairs()
File "generate_features.py", line 121, in distance_pairs
self.distance_matrix_ = mt.compute_distances(self.pdb, atom_pairs=all_pairs)[0]
File "/home/zjy/miniconda3/envs/drug_drug/lib/python3.6/site-packages/mdtraj/geometry/distance.py", line 62, in compute_distances
pairs = ensure_type(atom_pairs, dtype=np.int32, ndim=2, name='atom_pairs', shape=(None, 2), warn_on_cast=False)
File "/envs/drug_drug/lib/python3.6/site-packages/mdtraj/utils/validation.py", line 123, in ensure_type
"You supplied %s" % (name, ndim, val.ndim)))
ValueError: atom_pairs must be ndim 2. You supplied 1

ValueError: atom_pairs must be ndim 2. You supplied 1

**Comment by zengjianyou** [comment]
@zhenglz  
Like you said, pKa_relu is added to fn_train, and pKa_True is added to test, the program can work, thank you for your help, but I found that the RMSE of the core2016 data you gave the pre-training model can only reach 1.326,WHY?

**Comment by zhenglz** [comment]
In the file "generate_features.py" line 296:    n_cutoffs = np.linspace(0.1, 3.1, n_shells), please change 3.1 to 3.05. 
This could be error in the featurization. Please change the value, generate features, and run the prediction with v2016 coreset again, and please report the RMSE here. Thanks!

**Comment by zengjianyou** [comment]
> In the file "generate_features.py" line 296: n_cutoffs = np.linspace(0.1, 3.1, n_shells), please change 3.1 to 3.05.
> This could be error in the featurization. Please change the value, generate features, and run the prediction with v2016 coreset again, and please report the RMSE here. Thanks!

Have you tried？ in v2016 core-set，i got  1.327 RMSE

**Comment by dagger-neo** [comment]
> I successfully extracted your features, but an error occurred during my training, errors: No such column pKa_relu in input file ![image](https://user-images.githubusercontent.com/34835647/105141662-71c38c80-5b34-11eb-92e9-9855ed34b416.png)

I am facing the same problem (no such column as pKa_relu and key error in pKa_true) even after changing the name of the columns of the input files . 
The command i am using to train the algorithm is as follows-
python train.py -fn_train ..\onionnet-master\datasets\features_testing_v2013core_108_pka.csv -fn_validate ..\onionnet-master\datasets\features_testing_v2016core_290_pka.csv -fn_test ..\onionnet-master\datasets\input_codes_testing_core_v2016_290.csv -y_col pKa_relu pKa_true -prev_scaler models/StandardScaler.model -prev_model models/CNN_final_model_weights.h5 -log train.log -model new_tuned_model.h5 -scaler std_scaler.lib -epochs 10 -batch 32
Kindly help.
